baseURL = "https://arvola.com/"
defaultContentLanguage = "en"
languageCode = "en"
paginate = 5
theme = "texify"
title = "Arvola Woodwork"
relativeURLs = true
disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true

[author]
name = "Mikael"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "post"
  name = "Latest"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/post/"
  weight = 2
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3


[params]
  sitemapBase = "https://arvola.com/woodwork"
  relativeURLs = true
  customCSS = []
  dateFormat = "2006-01-02"
  description = "Mikael's woodworking journal."
  enableFullRSS = true
  favicon = "/favicon.ico"
  footnote = "lignum artificia"
  keywords = ["wood", "woodworking", "crafts", "projects"]

# see https://utteranc.es for installation guide
[params.utterances]
  enable = false
  repo = ""
  issue_term = "pathname"
  label = "Comment"
  theme = "github-light"
